import { useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarCheck2, Plus, ReceiptText, Trash2, WalletCards } from "lucide-react";
import MetricCard from "../components/ui/MetricCard";
import FormDialog from "../components/ui/FormDialog";
import { useGym } from "../context/GymContext";
import { useAuth } from "../context/AuthContext";

const money = (v) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(v);
const field = "h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:ring-2 focus:ring-[#E30613]/20";
const today = () => new Date().toISOString().slice(0,10);
const incomeCategories = ["Membresía", "Venta · Agua", "Venta · Energizante", "Venta · Proteína", "Venta · Suplementos", "Otro ingreso"];
const expenseCategories = ["Limpieza", "Insumos", "Luz", "Agua", "Alquiler", "Mantenimiento", "Sueldos", "Retiro de caja", "Otro gasto"];

export default function Caja() {
  const { data, addTransaction, deleteTransaction, closeCash } = useGym();
  const { permissions } = useAuth();
  const [kind, setKind] = useState(null); const [closing, setClosing] = useState(false);
  const day = data.transactions.filter((t) => t.branch === data.activeBranch && t.date === today());
  const income = day.filter((t) => t.type === "income").reduce((s,t) => s+t.amount,0);
  const expense = day.filter((t) => t.type === "expense").reduce((s,t) => s+t.amount,0);
  const submit = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); addTransaction({ type: kind, category: f.get("category"), detail: f.get("detail"), amount: f.get("amount"), method: f.get("method"), date: f.get("date") }); setKind(null); };
  const doClose = (e) => { e.preventDefault(); closeCash(new FormData(e.currentTarget).get("actual")); setClosing(false); };
  const closures = data.closures.filter((closure) => closure.branch === data.activeBranch).slice(0, 7);
  const removeTransaction = (transaction) => { if (window.confirm(`¿Eliminar el movimiento “${transaction.detail}”?`)) deleteTransaction(transaction.id); };

  return <div className="mx-auto max-w-[1480px] space-y-6"><section className="page-head"><div><p className="eyebrow">Finanzas</p><h1 className="page-title">Caja diaria</h1><p className="page-subtitle">Ingresos, gastos y cierre por sucursal.</p></div><div className="flex gap-2"><button onClick={() => setKind("expense")} className="btn-secondary"><ReceiptText className="size-4"/> Gasto</button><button onClick={() => setKind("income")} className="btn-primary"><Plus className="size-4"/> Ingreso</button></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><MetricCard label="Ingresos" value={money(income)} detail={`${day.filter(t=>t.type==="income").length} operaciones`} icon={ArrowDownLeft}/><MetricCard label="Gastos" value={money(expense)} detail={`${day.filter(t=>t.type==="expense").length} operaciones`} icon={ArrowUpRight} tone="orange"/><MetricCard label="Saldo esperado" value={money(income-expense)} detail="Caja abierta" icon={WalletCards} tone="red"/></section>
    <section className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><article className="panel"><h2 className="section-title">Movimientos de hoy</h2><div className="mt-4 divide-y divide-slate-100">{day.map(t=><div key={t.id} className="flex items-center gap-3 py-4"><span className={`grid size-10 place-items-center rounded-xl ${t.type==="income"?"bg-red-50 text-[#E30613]":"bg-[#DADADA] text-[#9E0710]"}`}>{t.type==="income"?<ArrowDownLeft className="size-5"/>:<ArrowUpRight className="size-5"/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{t.detail}</p><p className="text-xs text-slate-400">{t.category} · {t.method}</p></div><strong className={t.type==="income"?"text-[#E30613]":"text-slate-700"}>{t.type==="income"?"+":"−"} {money(t.amount)}</strong>{permissions?.canDelete && <button onClick={()=>removeTransaction(t)} aria-label={`Eliminar ${t.detail}`} className="text-slate-300 hover:text-[#9E0710]"><Trash2 className="size-4"/></button>}</div>)}{!day.length&&<p className="py-12 text-center text-sm text-slate-400">Todavía no hay movimientos.</p>}</div></article><article className="rounded-[24px] bg-[#050505] p-6 text-white"><WalletCards className="size-8 text-[#E30613]"/><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-[#AFAFAF]">Saldo de la jornada</p><p className="mt-2 text-4xl font-black">{money(income-expense)}</p><p className="mt-3 text-sm text-[#AFAFAF]">El cierre guarda el efectivo contado y cualquier diferencia.</p><button onClick={()=>setClosing(true)} className="mt-8 h-11 w-full rounded-xl bg-[#E30613] text-sm font-black text-white">Realizar cierre</button></article></section>
    <section className="panel"><div className="flex items-center gap-3"><CalendarCheck2 className="size-5 text-[#E30613]"/><div><h2 className="section-title">Últimos cierres</h2><p className="text-xs text-slate-500">Saldo esperado, contado y diferencia.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="table-head"><th>Fecha</th><th>Esperado</th><th>Contado</th><th className="text-right">Diferencia</th></tr></thead><tbody className="divide-y divide-slate-100">{closures.map(c=><tr key={c.id}><td className="py-4 text-sm font-bold">{new Date(c.date).toLocaleString("es-AR")}</td><td>{money(c.expected)}</td><td>{money(c.actual)}</td><td className={`text-right font-black ${c.difference===0?"text-slate-700":c.difference>0?"text-[#E30613]":"text-[#9E0710]"}`}>{money(c.difference)}</td></tr>)}</tbody></table>{!closures.length&&<p className="py-8 text-center text-sm text-slate-400">Todavía no hay cierres registrados.</p>}</div></section>
    <FormDialog open={!!kind} onOpenChange={(v)=>!v&&setKind(null)} title={kind==="income"?"Registrar ingreso o venta":"Registrar gasto"} description="Quedará incluido en la caja y en los reportes."><form onSubmit={submit} className="grid gap-4"><label>Fecha<input name="date" type="date" required defaultValue={today()} className={field}/></label><label>Concepto<input name="detail" required placeholder={kind==="income"?"Ej. 2 aguas minerales":"Ej. Artículos de limpieza"} className={field}/></label><label>Categoría<select name="category" className={field}>{(kind==="income"?incomeCategories:expenseCategories).map((category)=><option key={category}>{category}</option>)}</select></label><label>Importe total<input name="amount" required type="number" min="1" className={field}/></label><label>Medio<select name="method" className={field}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><button className="btn-primary">Guardar movimiento</button></form></FormDialog>
    <FormDialog open={closing} onOpenChange={setClosing} title="Cierre de caja" description={`Saldo esperado: ${money(income-expense)}`}><form onSubmit={doClose} className="grid gap-4"><label>Efectivo/saldo contado<input name="actual" type="number" required defaultValue={income-expense} className={field}/></label><button className="btn-primary">Confirmar cierre</button></form></FormDialog>
  </div>;
}
