import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CreditCard, Pencil, Plus, Search, Trash2 } from "lucide-react";
import FormDialog from "../components/ui/FormDialog";
import { statusOf, useGym } from "../context/GymContext";
import { useAuth } from "../context/AuthContext";

const PAGE_SIZE = 100;
const input = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#E30613]/20";

export default function Clientes() {
  const { data, addPerson, editPerson, deletePerson, renew } = useGym();
  const { permissions } = useAuth();
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(0);
  const [adding, setAdding] = useState(false);
  const [renewing, setRenewing] = useState(null);
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState("");
  const clients = useMemo(() => data.people.filter((p) => p.role === "Cliente" && p.branch === data.activeBranch && `${p.name} ${p.dni}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const pageCount = Math.max(1, Math.ceil(clients.length / PAGE_SIZE));
  const safePage = Math.min(page, pageCount - 1);
  const visibleClients = clients.slice(safePage * PAGE_SIZE, (safePage + 1) * PAGE_SIZE);
  const submitPerson = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const start = new Date(); const end = new Date(start); end.setMonth(end.getMonth() + 1); const result = addPerson({ name: f.get("name").trim(), dni: f.get("dni").trim(), phone: f.get("phone").trim(), role: "Cliente", plan: f.get("plan"), price: Number(f.get("price")), biometricMethod: f.get("biometricMethod"), biometricStatus: f.get("biometricMethod") === "Sin registrar" ? "Pendiente" : "Listo para vincular", initialPayment: f.get("initialPayment") === "on", discount: Number(f.get("discount")), method: f.get("method"), start: start.toISOString().slice(0,10), expiry: end.toISOString().slice(0,10) }); if (!result.ok) { setError(result.error); return; } setError(""); setAdding(false); };
  const submitEdit = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const result = editPerson(editing.id, { name: f.get("name").trim(), dni: f.get("dni").trim(), phone: f.get("phone").trim(), plan: f.get("plan"), price: Number(f.get("price")), biometricMethod: f.get("biometricMethod"), biometricStatus: f.get("biometricMethod") === "Sin registrar" ? "Pendiente" : "Listo para vincular" }); if (!result.ok) { setError(result.error); return; } setError(""); setEditing(null); };
  const remove = (person) => { if (window.confirm(`¿Eliminar a ${person.name}? Sus movimientos financieros se conservarán.`)) deletePerson(person.id); };
  const submitRenew = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); renew(renewing.id, { months: f.get("months"), discount: f.get("discount"), method: f.get("method") }); setRenewing(null); };
  const changeQuery = (value) => { setQuery(value); setPage(0); };

  return <div className="mx-auto max-w-[1480px] space-y-4 sm:space-y-6">
    <section className="page-head"><div><p className="eyebrow">Personas</p><h1 className="page-title">Clientes</h1><p className="page-subtitle">Alumnos, planes y vencimientos de la sucursal activa.</p></div>{permissions?.canOperate && <button onClick={() => setAdding(true)} className="btn-primary"><Plus className="size-4" /> Nuevo cliente</button>}</section>
    <section className="panel p-3.5 sm:p-5"><label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 focus-within:ring-2 focus-within:ring-[#E30613]/15"><Search className="size-4 shrink-0 text-slate-400" /><input value={query} onChange={(e) => changeQuery(e.target.value)} className="min-w-0 w-full bg-transparent text-sm outline-none" placeholder="Buscar por nombre o DNI" /></label>

      <div className="mt-4 space-y-3 md:hidden">{visibleClients.map((person) => { const status = statusOf(person); return <article key={person.id} className="rounded-2xl border border-black/7 bg-white p-3.5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-black text-slate-800">{person.name}</p><p className="mt-1 text-xs font-bold text-slate-400">DNI {person.dni} · {person.plan}</p></div><span className={`status shrink-0 ${status === "Vigente" ? "status-ok" : status === "Por vencer" ? "status-warn" : "status-bad"}`}>{status}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl bg-slate-50 p-2.5"><p className="text-[10px] font-black uppercase text-slate-400">Vencimiento</p><p className="mt-1 text-xs font-black text-slate-700">{new Date(person.expiry + "T12:00:00").toLocaleDateString("es-AR")}</p></div><div className="rounded-xl bg-slate-50 p-2.5"><p className="text-[10px] font-black uppercase text-slate-400">Biometría</p><p className="mt-1 truncate text-xs font-black text-slate-700">{person.biometricMethod || "Sin registrar"}</p></div></div>{permissions?.canOperate && <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => setRenewing(person)} className="btn-primary min-h-10"><CreditCard className="size-4" /> Renovar</button><button onClick={() => { setError(""); setEditing(person); }} className="btn-secondary min-h-10"><Pencil className="size-4" /> Editar</button></div>}</article>; })}{!clients.length && <p className="py-10 text-center text-sm text-slate-400">No hay clientes para mostrar.</p>}</div>

      <div className="mt-5 hidden overflow-x-auto md:block"><table className="w-full min-w-[940px] text-left"><thead><tr className="table-head"><th>Cliente</th><th>Plan</th><th>Biometría</th><th>Vencimiento</th><th>Estado</th><th className="text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleClients.map((person) => { const status = statusOf(person); return <tr key={person.id}><td className="py-4"><p className="font-bold text-slate-800">{person.name}</p><p className="text-xs text-slate-400">DNI {person.dni}</p></td><td>{person.plan}</td><td><span className="status status-ok">{person.biometricMethod || "Sin registrar"}</span></td><td>{new Date(person.expiry + "T12:00:00").toLocaleDateString("es-AR")}</td><td><span className={`status ${status === "Vigente" ? "status-ok" : status === "Por vencer" ? "status-warn" : "status-bad"}`}>{status}</span></td><td><div className="flex justify-end gap-3">{permissions?.canOperate ? <><button onClick={() => setRenewing(person)} className="inline-flex items-center gap-1 text-sm font-black text-[#E30613]"><CreditCard className="size-4" /> Renovar</button><button onClick={() => { setError(""); setEditing(person); }} className="inline-flex items-center gap-1 text-sm font-black text-slate-600"><Pencil className="size-4" /> Editar</button>{permissions?.canDelete && <button onClick={() => remove(person)} className="inline-flex items-center gap-1 text-sm font-black text-[#9E0710]" aria-label={`Eliminar a ${person.name}`}><Trash2 className="size-4" /></button>}</> : <span className="text-xs font-bold text-slate-400">Solo lectura</span>}</div></td></tr>; })}</tbody></table>{!clients.length && <p className="py-12 text-center text-sm text-slate-400">No hay clientes para mostrar.</p>}</div>

      {clients.length > PAGE_SIZE && <div className="mt-5 flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-bold text-slate-400">{safePage * PAGE_SIZE + 1}–{Math.min((safePage + 1) * PAGE_SIZE, clients.length)} de {clients.length}</p><div className="flex gap-2"><button onClick={() => setPage(Math.max(0, safePage - 1))} disabled={safePage === 0} className="btn-secondary px-3 disabled:opacity-40"><ChevronLeft className="size-4" /> Anterior</button><span className="grid min-w-16 place-items-center text-xs font-black text-slate-500">{safePage + 1} / {pageCount}</span><button onClick={() => setPage(Math.min(pageCount - 1, safePage + 1))} disabled={safePage >= pageCount - 1} className="btn-secondary px-3 disabled:opacity-40">Siguiente <ChevronRight className="size-4" /></button></div></div>}
    </section>
    <FormDialog open={adding} onOpenChange={(value) => { setAdding(value); setError(""); }} title="Nuevo cliente" description="La membresía inicial será válida por un mes."><form onSubmit={submitPerson} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Nombre completo<input name="name" required className={input} /></label><label>DNI<input name="dni" inputMode="numeric" pattern="[0-9]+" required className={input} /></label><label>Teléfono<input name="phone" className={input} /></label><label>Plan<select name="plan" className={input}><option>Full</option><option>3 días</option></select></label><label>Precio mensual<input name="price" required type="number" min="0" defaultValue="45000" className={input} /></label><label>Descuento inicial %<input name="discount" type="number" min="0" max="100" defaultValue="0" className={input} /></label><label>Medio de pago<select name="method" className={input}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><label className="sm:col-span-2">Dato biométrico<select name="biometricMethod" className={input}><option>Sin registrar</option><option>Huella</option><option>Reconocimiento facial</option></select></label><label className="sm:col-span-2 flex items-center gap-3 rounded-xl bg-[#F5F5F5] p-3 text-sm font-bold"><input name="initialPayment" type="checkbox" defaultChecked className="size-4 accent-[#E30613]" /> Registrar también el pago inicial</label>{error && <p className="sm:col-span-2 text-sm font-bold text-red-600">{error}</p>}<button className="btn-primary sm:col-span-2">Guardar cliente</button></form></FormDialog>
    <FormDialog open={!!editing} onOpenChange={(value) => { if (!value) setEditing(null); setError(""); }} title={`Editar a ${editing?.name || ""}`} description="Actualizá sus datos y la opción biométrica."><form onSubmit={submitEdit} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Nombre completo<input name="name" required defaultValue={editing?.name} className={input} /></label><label>DNI<input name="dni" required inputMode="numeric" pattern="[0-9]+" defaultValue={editing?.dni} className={input} /></label><label>Teléfono<input name="phone" defaultValue={editing?.phone} className={input} /></label><label>Plan<select name="plan" defaultValue={editing?.plan} className={input}><option>Full</option><option>3 días</option></select></label><label>Precio mensual<input name="price" required type="number" min="0" defaultValue={editing?.price} className={input} /></label><label className="sm:col-span-2">Dato biométrico<select name="biometricMethod" defaultValue={editing?.biometricMethod || "Sin registrar"} className={input}><option>Sin registrar</option><option>Huella</option><option>Reconocimiento facial</option></select></label>{error && <p className="sm:col-span-2 text-sm font-bold text-red-600">{error}</p>}<button className="btn-primary sm:col-span-2">Guardar cambios</button></form></FormDialog>
    <FormDialog open={!!renewing} onOpenChange={(v) => !v && setRenewing(null)} title={`Renovar a ${renewing?.name || ""}`} description="Se registra el pago y extiende el vencimiento."><form onSubmit={submitRenew} className="grid gap-4 sm:grid-cols-2"><label>Meses<input name="months" type="number" min="1" defaultValue="1" className={input} /></label><label>Descuento %<input name="discount" type="number" min="0" max="100" defaultValue="0" className={input} /></label><label className="sm:col-span-2">Medio de pago<select name="method" className={input}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><button className="btn-primary sm:col-span-2">Confirmar renovación</button></form></FormDialog>
  </div>;
}
