import { useMemo, useState } from "react";
import { CreditCard, Pencil, Plus, Search, Trash2 } from "lucide-react";
import FormDialog from "../components/ui/FormDialog";
import { statusOf, useGym } from "../context/GymContext";
import { useAuth } from "../context/AuthContext";

const input = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#E30613]/20";

export default function Clientes() {
  const { data, addPerson, editPerson, deletePerson, renew } = useGym();
  const { permissions } = useAuth();
  const [query, setQuery] = useState("");
  const [adding, setAdding] = useState(false);
  const [renewing, setRenewing] = useState(null);
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState("");
  const clients = useMemo(() => data.people.filter((p) => p.role === "Cliente" && p.branch === data.activeBranch && `${p.name} ${p.dni} ${p.email || ""}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const submitPerson = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const start = new Date(); const end = new Date(start); end.setMonth(end.getMonth() + 1); const result = addPerson({ name: f.get("name").trim(), dni: f.get("dni").trim(), email: String(f.get("email") || "").trim().toLowerCase(), phone: f.get("phone").trim(), role: "Cliente", plan: f.get("plan"), price: Number(f.get("price")), biometricMethod: f.get("biometricMethod"), biometricStatus: f.get("biometricMethod") === "Sin registrar" ? "Pendiente" : "Listo para vincular", initialPayment: f.get("initialPayment") === "on", discount: Number(f.get("discount")), method: f.get("method"), start: start.toISOString().slice(0,10), expiry: end.toISOString().slice(0,10) }); if (!result.ok) { setError(result.error); return; } setError(""); setAdding(false); };
  const submitEdit = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const result = editPerson(editing.id, { name: f.get("name").trim(), dni: f.get("dni").trim(), email: String(f.get("email") || "").trim().toLowerCase(), phone: f.get("phone").trim(), plan: f.get("plan"), price: Number(f.get("price")), biometricMethod: f.get("biometricMethod"), biometricStatus: f.get("biometricMethod") === "Sin registrar" ? "Pendiente" : "Listo para vincular" }); if (!result.ok) { setError(result.error); return; } setError(""); setEditing(null); };
  const remove = (person) => { if (window.confirm(`¿Eliminar a ${person.name}? Sus movimientos financieros se conservarán.`)) deletePerson(person.id); };
  const submitRenew = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); renew(renewing.id, { months: f.get("months"), discount: f.get("discount"), method: f.get("method") }); setRenewing(null); };

  return <div className="mx-auto max-w-[1480px] space-y-6">
    <section className="page-head"><div><p className="eyebrow">Personas</p><h1 className="page-title">Clientes</h1><p className="page-subtitle">Altas, planes, vencimientos y renovaciones.</p></div>{permissions?.canOperate && <button onClick={() => setAdding(true)} className="btn-primary"><Plus className="size-4" /> Nuevo cliente</button>}</section>
    <section className="panel"><label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 focus-within:ring-2 focus-within:ring-[#E30613]/15"><Search className="size-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Buscar por nombre, DNI o email" /></label>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[940px] text-left"><thead><tr className="table-head"><th>Cliente</th><th>Cuenta PWA</th><th>Plan</th><th>Biometría</th><th>Vencimiento</th><th>Estado</th><th className="text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{clients.map((person) => { const status = statusOf(person); return <tr key={person.id}><td className="py-4"><p className="font-bold text-slate-800">{person.name}</p><p className="text-xs text-slate-400">DNI {person.dni}</p></td><td>{person.email ? <span className="text-xs font-bold text-emerald-700">{person.email}</span> : <span className="text-xs text-slate-400">Sin vincular</span>}</td><td>{person.plan}</td><td><span className="status status-ok">{person.biometricMethod || "Sin registrar"}</span></td><td>{new Date(person.expiry + "T12:00:00").toLocaleDateString("es-AR")}</td><td><span className={`status ${status === "Vigente" ? "status-ok" : status === "Por vencer" ? "status-warn" : "status-bad"}`}>{status}</span></td><td><div className="flex justify-end gap-3">{permissions?.canOperate ? <><button onClick={() => setRenewing(person)} className="inline-flex items-center gap-1 text-sm font-black text-[#E30613]"><CreditCard className="size-4" /> Renovar</button><button onClick={() => { setError(""); setEditing(person); }} className="inline-flex items-center gap-1 text-sm font-black text-slate-600"><Pencil className="size-4" /> Editar</button>{permissions?.canDelete && <button onClick={() => remove(person)} className="inline-flex items-center gap-1 text-sm font-black text-[#9E0710]" aria-label={`Eliminar a ${person.name}`}><Trash2 className="size-4" /></button>}</> : <span className="text-xs font-bold text-slate-400">Solo lectura</span>}</div></td></tr>; })}</tbody></table>{!clients.length && <p className="py-12 text-center text-sm text-slate-400">No hay clientes para mostrar.</p>}</div>
    </section>
    <FormDialog open={adding} onOpenChange={(value) => { setAdding(value); setError(""); }} title="Nuevo cliente" description="La membresía inicial será válida por un mes."><form onSubmit={submitPerson} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Nombre completo<input name="name" required className={input} /></label><label>DNI<input name="dni" inputMode="numeric" pattern="[0-9]+" required className={input} /></label><label>Email PWA<input name="email" type="email" placeholder="cuenta@gmail.com" className={input} /></label><label>Teléfono<input name="phone" className={input} /></label><label>Plan<select name="plan" className={input}><option>Full</option><option>3 días</option></select></label><label>Precio mensual<input name="price" required type="number" min="0" defaultValue="45000" className={input} /></label><label>Descuento inicial %<input name="discount" type="number" min="0" max="100" defaultValue="0" className={input} /></label><label>Medio de pago<select name="method" className={input}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><label className="sm:col-span-2">Dato biométrico<select name="biometricMethod" className={input}><option>Sin registrar</option><option>Huella</option><option>Reconocimiento facial</option></select></label><label className="sm:col-span-2 flex items-center gap-3 rounded-xl bg-[#F5F5F5] p-3 text-sm font-bold"><input name="initialPayment" type="checkbox" defaultChecked className="size-4 accent-[#E30613]" /> Registrar también el pago inicial</label>{error && <p className="sm:col-span-2 text-sm font-bold text-red-600">{error}</p>}<button className="btn-primary sm:col-span-2">Guardar cliente</button></form></FormDialog>
    <FormDialog open={!!editing} onOpenChange={(value) => { if (!value) setEditing(null); setError(""); }} title={`Editar a ${editing?.name || ""}`} description="Actualizá sus datos y la opción biométrica."><form onSubmit={submitEdit} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Nombre completo<input name="name" required defaultValue={editing?.name} className={input} /></label><label>DNI<input name="dni" required inputMode="numeric" pattern="[0-9]+" defaultValue={editing?.dni} className={input} /></label><label>Email PWA<input name="email" type="email" defaultValue={editing?.email || ""} placeholder="cuenta@gmail.com" className={input} /></label><label>Teléfono<input name="phone" defaultValue={editing?.phone} className={input} /></label><label>Plan<select name="plan" defaultValue={editing?.plan} className={input}><option>Full</option><option>3 días</option></select></label><label>Precio mensual<input name="price" required type="number" min="0" defaultValue={editing?.price} className={input} /></label><label className="sm:col-span-2">Dato biométrico<select name="biometricMethod" defaultValue={editing?.biometricMethod || "Sin registrar"} className={input}><option>Sin registrar</option><option>Huella</option><option>Reconocimiento facial</option></select></label>{error && <p className="sm:col-span-2 text-sm font-bold text-red-600">{error}</p>}<button className="btn-primary sm:col-span-2">Guardar cambios</button></form></FormDialog>
    <FormDialog open={!!renewing} onOpenChange={(v) => !v && setRenewing(null)} title={`Renovar a ${renewing?.name || ""}`} description="Se registra el pago y extiende el vencimiento."><form onSubmit={submitRenew} className="grid gap-4 sm:grid-cols-2"><label>Meses<input name="months" type="number" min="1" defaultValue="1" className={input} /></label><label>Descuento %<input name="discount" type="number" min="0" max="100" defaultValue="0" className={input} /></label><label className="sm:col-span-2">Medio de pago<select name="method" className={input}><option>Efectivo</option><option>Transferencia</option><option>Tarjeta</option></select></label><button className="btn-primary sm:col-span-2">Confirmar renovación</button></form></FormDialog>
  </div>;
}
